# Generated by Django 6.1 on 2026-08-31 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('buying_options', models.JSONField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('item_url', models.TextField(blank=True, null=True)),
                ('affiliate_url', models.TextField(blank=True, null=True)),
                ('seller_username', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_feedback_score', models.IntegerField(blank=True, null=True)),
                ('seller_feedback_percent', models.FloatField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=100, null=True)),
                ('item_country', models.CharField(blank=True, max_length=2, null=True)),
                ('item_city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('item_created_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_summaries',
            },
        ),
    ]
