# Generated by Django 6.1 on 2026-09-01 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SOLD', 'Sold')], default='ACTIVE', max_length=20)),
                ('affiliate_url', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('miss_count', models.IntegerField(blank=True, default=0)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
                'indexes': [models.Index(fields=['status', 'country', '-last_updated'], name='ix_status_country_updated')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing')),
            ],
            options={
                'db_table': 'price_history',
                'indexes': [models.Index(fields=['listing', 'recorded_at', 'id'], name='ix_pricehistory_listing_time')],
            },
        ),
    ]
