# Generated by Django 6.1 on 2026-09-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='listings.systems')),
            ],
        ),
    ]
