# Generated by Django 6.1 on 2026-09-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_systemalias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemalias',
            table='aliases',
        ),
    ]
