# Generated by Django 6.1 on 2026-09-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_systemalias_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.systems'),
        ),
    ]
